name: al_heedh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Packages yang Sudah Ada
  shared_preferences: ^2.2.3 # Untuk menyimpan nama pengguna
  http: ^1.2.1               # Untuk integrasi API waktu salat
  html: ^0.15.4              # Untuk parsing HTML jadwal sholat

  # Packages Baru untuk Fungsionalitas Inti
  table_calendar: ^3.1.1     # Untuk tampilan kalender interaktif
  hive: ^2.2.3               # Database lokal cepat untuk menyimpan catatan haid
  hive_flutter: ^1.1.0       # Integrasi Hive dengan Flutter
  intl: ^0.19.0              # Untuk format tanggal dan lokal bahasa Indonesia
  geolocator: ^12.0.0        # Untuk mendapatkan lokasi pengguna
  flutter_local_notifications: ^17.2.2 # Untuk notifikasi lokal
  timezone: ^0.9.4           # Untuk scheduling notifikasi dengan timezone
  url_launcher: ^6.2.3       # Untuk membuka WhatsApp

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Dev dependencies untuk Hive (PENTING: Perlu menjalankan build_runner)
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

# Konfigurasi Aset Gambar
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.apk.png
    - assets/images/jadwal sholat.jpg
    - assets/images/artikel.jpg
    - assets/images/wirid dan doa.jpg
    - assets/silhouette.png
 
